server:
  port: 8021
spring:
  application:
    name: Zuul-Application
eureka:
  instance:
    instance-id: instanceId-ZuulApplication
    prefer-ip-address: true
  client:
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/

zuul:
  #ignored-services: microservicecloud-dept
  #prefix: /abc
  #ignored-services: "*"
  routes:
    aaa.serviceId: Producer-Application
    aaa.path: /aaa/**