server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
spring:
  application:
    name: eureka7001-Application