server:
  port: 8401

spring:
  application:
    name:  Config-Application
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/microservicecloud-config.git #GitHub上面的git仓库名字